version: 0.1
phases:
  pre_build:
    commands:
     - echo "${PRIVATE_KEY}" > ./.codebuild/id_rsa
     - echo "${HOSTS}" > ./.codebuild/hosts
     - echo "${KEY}" > ./.codebuild/GIT_KEY
     - chmod 400 ./.codebuild/GIT_KEY 
     - chmod 400 ./.codebuild/id_rsa
  build:
    commands:
      - |
        cd .codebuild && \
        ansible-playbook main.yml -vvv 